// Three 0-100% dials summarizing a run from different angles (owner request).
// Deliberately separate lenses on the same data — and, since the rework below,
// actually independent of one another rather than three views of the same
// lucky draw.
//
// WHAT WAS WRONG, because the shape of the fix only makes sense next to it.
// Skill was Decision Rating, and Decision Rating was `actualScore / bestEV` —
// one realised draw divided by a mean over every possible draw. Both Skill and
// Luck were therefore driven by the same variable, `actualScore`, which is why
// a single fortunate hand pinned both dials at 100% simultaneously. Measured
// over 200 deals played three ways each:
//
//   - the mathematically OPTIMAL discard read under 50% Skill 82.5% of the
//     time, with a median of 8%;
//   - the WORST legal discard out-read the optimal one on 6% of deals;
//   - Luck correlated -0.49 with choice quality: playing badly lowered the bar
//     Luck graded you against, so bad players looked luckier.
//
// The split now follows the actual causality of a run. Skill owns the part the
// player decided (which discard, priced before any card moves). Luck owns the
// part the deck decided (what the deal offered, and what the draw delivered).
// Neither can move the other. See ev-solver.js's choiceQuality() and
// drawPercentile() for the two measurements themselves.

import { scoreForHandId } from './hand-evaluator.js';

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

// Generated by tools/calibrate-meters.js from 1,500 deals through the real
// dealHand() path (wild cards and all — the previous calibration sampled
// createDeck/shuffle and had never seen one). bestEV at each 5th percentile,
// p0 through p100.
//
// A TABLE RATHER THAN A CEILING because the distribution is nowhere near
// linear: p10 ≈ 2,000, p50 ≈ 6,000, p90 ≈ 44,000, max in the millions, since
// HAND_RANKS is odds-proportional and the mean chases rare enormous hands.
// The old single `DEAL_QUALITY_CEILING = 8000` sat at about the 62nd
// percentile of real deals, so roughly 38% of them showed this half of Luck
// pinned at a full 100%. Interpolating percentile stops makes the dial uniform
// by construction — half of deals read above 50% because half of deals are.
const DEAL_QUALITY_STOPS = [
  1000, 1770, 2216, 2387, 2650, 2973, 3510,
  4465, 4998, 5535, 5982, 6648, 7802, 9916,
  14890, 16614, 19921, 32791, 44779, 70512, 7989665,
];

// THE NO-DISCARD YARDSTICK. Double or Nothing (§4e) sets maxDiscards to 0, so
// "what a perfect player could get out of this deal" collapses to "what these
// five cards are already worth" — a small fraction of what the same deal is
// worth with three draws available. Measured against the table above, every
// player on a wager day read a deal quality of about 3%: a real number scored
// against the wrong distribution, which is the same mistake as the ceiling it
// replaced, one level down.
//
// Generated by tools/calibrate-meters.js from 40,000 deals (no solving needed
// for this one, hence the much larger sample). Opening-hand score at each 5th
// percentile. The flat run of zeroes at the bottom is real and not a bug —
// over 30% of opening hands are a bare High Card worth nothing, so they tie,
// and they all read 0%.
//
// SWITCHED ON maxDiscards, NOT ON WHAT THE PLAYER DID. Choosing to hold pat on
// an ordinary day is a decision, and the deal's value there is still its
// three-discard potential — the player simply declined to use it. Only a day
// that forbids discarding changes what the deal was ever worth.
const PAT_QUALITY_STOPS = [
  0, 0, 0, 0, 0, 0, 0,
  135, 161, 187, 213, 239, 265, 473,
  557, 669, 725, 1717, 2600, 3745, 54800000,
];

// Where `value` falls in a sorted table of percentile stops, 0-1, linearly
// interpolated between neighbours and flat outside the ends.
function percentileFromStops(value, stops) {
  if (!Number.isFinite(value)) return null;
  if (value <= stops[0]) return 0;
  const last = stops.length - 1;
  if (value >= stops[last]) return 1;
  for (let i = 1; i <= last; i++) {
    if (value <= stops[i]) {
      const span = stops[i] - stops[i - 1];
      const within = span === 0 ? 0 : (value - stops[i - 1]) / span;
      return (i - 1 + within) / last;
    }
  }
  return 1;
}

/**
 * Luck's deal half on its own, 0-100, for the "?" panel — which explains the
 * dial by naming its two inputs separately, so it needs the halves rather than
 * the blend. Exported from here rather than recomputed at the call site so the
 * number the panel quotes is provably the number the meter used.
 *
 * @param {number} dealBestEV
 * @param {{maxDiscards?: number}} [options] - `maxDiscards: 0` selects the
 *   pat-hand table; see PAT_QUALITY_STOPS.
 * @returns {number|null} null when there is no EV to place.
 */
export function dealQualityPercent(dealBestEV, { maxDiscards = 3 } = {}) {
  const stops = maxDiscards === 0 ? PAT_QUALITY_STOPS : DEAL_QUALITY_STOPS;
  const quality = percentileFromStops(dealBestEV, stops);
  return quality === null ? null : quality * 100;
}

const RISK_DISCARD_WEIGHT = 60;
const RISK_CHASE_WEIGHT = 40;
// What counts as "already holding something worth protecting" for the chase
// half of Risk — a Three of a Kind and up saturates it.
//
// This used to normalize against ROYAL_FLUSH (54,800,000), which made the
// entire chase component numerically inert: since real hands score in the
// hundreds to tens of thousands, every category below Straight Flush
// contributed LESS THAN ONE POINT of the 40 available (Two Pair: 0.001).
// Risk was therefore just discardedCount/maxDiscards × 60, capped at 60 —
// and "The Gambler" personality (personality.js), which needs risk >= 65,
// was unreachable without being dealt a Royal Flush and throwing it away.
// The ROYAL_FLUSH anchor was a leftover from before HAND_RANKS was rescaled
// to be odds-proportional (hand-evaluator.js), when the top of the table was
// ~5,000 rather than ~55,000,000 and dividing by it was reasonable.
//
// Re-measured over 4,000 deals during the Skill/Luck rework and left alone:
// opening hands run p50 = 213 and p95 = 3,830 against this 4,000 ceiling, so
// discarding three reaches 62% Risk on a median hand and 98% on a strong one.
// The dial spans its range and The Gambler is reachable. Nothing to fix.
const RISK_CHASE_CEILING = scoreForHandId('THREE_OF_A_KIND');

/**
 * @param {object} params
 * @param {{score: number}} params.originalHandResult - evaluateHand() on the opening hand
 * @param {number|null} params.decisionRating - choiceQuality() from ev-solver:
 *   where the chosen discard ranked among the legal ones, 0-1, or null when
 *   there was no decision to grade
 * @param {number} params.dealBestEV - EV of the best discard for this deal, i.e.
 *   how much this starting hand was worth to a perfect player
 * @param {number|null} params.drawPercentile - drawPercentile() from ev-solver:
 *   the fraction of possible draws the realised one beat, or null if no cards
 *   were drawn
 * @param {number} params.discardedCount
 * @param {number} params.maxDiscards
 * @returns {{luck: number|null, skill: number|null, risk: number}} each 0-100
 *   and rounded, or null for "not measured" — never a placeholder value.
 */
export function computeMeters({
  originalHandResult,
  decisionRating,
  dealBestEV,
  drawPercentile,
  discardedCount,
  maxDiscards,
}) {
  // NULL, NOT 100. This used to read `Number.isFinite(decisionRating) ?
  // decisionRating : 1`, so an unmeasurable run — a Double or Nothing round,
  // which locks in with zero discards and therefore offers no choice at all —
  // silently displayed a full 100% Skill bar. board.js hides the Decision
  // Rating line in exactly that case, with a comment explaining that 0% would
  // be as untrue as 100%; the meter directly underneath it was showing 100%
  // the whole time. A default that fires on the "we don't know" branch is a
  // claim, and this one was the most flattering claim available.
  const skill = decisionRating === null || !Number.isFinite(decisionRating)
    ? null
    : clamp(Math.round(decisionRating * 100), 0, 100);

  // Luck is everything the player did not decide, in the two places the deck
  // gets to speak: what it dealt, and what it drew.
  const dealPercent = dealQualityPercent(dealBestEV, { maxDiscards });
  const dealQuality = dealPercent === null ? null : dealPercent / 100;
  const drewSomething = Number.isFinite(drawPercentile);
  let luck = null;
  if (dealQuality === null) {
    // No solve to measure the deal against — fall back to the draw alone
    // rather than inventing a deal quality.
    luck = drewSomething ? clamp(Math.round(drawPercentile * 100), 0, 100) : null;
  } else if (drewSomething) {
    luck = clamp(Math.round(((dealQuality + drawPercentile) / 2) * 100), 0, 100);
  } else {
    // Held pat: there was no draw to be lucky about, so the deal IS the whole
    // story. Averaging against a missing half would drag every stand-pat run
    // toward the middle and make a dealt-pat Straight Flush read as ordinary.
    luck = clamp(Math.round(dealQuality * 100), 0, 100);
  }

  // Risk is 0 for holding pat — nothing was gambled. Otherwise it scales
  // with how much of the hand was let go, boosted by how much value was
  // already in the original hand (abandoning a decent hand to chase
  // something else is riskier than tossing a hopeless one).
  let risk = 0;
  if (discardedCount > 0 && maxDiscards > 0) {
    const baseRisk = (discardedCount / maxDiscards) * RISK_DISCARD_WEIGHT;
    const chaseBonus = clamp(originalHandResult.score / RISK_CHASE_CEILING, 0, 1) * RISK_CHASE_WEIGHT;
    risk = clamp(Math.round(baseRisk + chaseBonus), 0, 100);
  }

  return { luck, skill, risk };
}
