// One-off calibration script (not part of the app runtime) — samples random
// deals, runs the real EV solver against each, and prints the DEAL_QUALITY_STOPS
// table that meters.js pastes in for Luck's deal half. Run with:
//   node tools/calibrate-meters.js [samples]
//
// TWO THINGS THIS SCRIPT USED TO GET WRONG, both worth keeping written down.
//
// 1. IT DEALT FROM THE WRONG FUNCTION. It built hands with createDeck/shuffle
//    directly, which is not how the game deals: dealHand() also rolls a rarity
//    and a wild flag per card (§3x). So this sampler had never seen a wild card
//    in its life, and wilds are exactly the cards that produce the enormous
//    hands the top of the distribution is made of. It reported bestEV p90 ≈
//    9,300; through the real deal path it is ≈ 44,000. DEAL_QUALITY_CEILING was
//    set to 8,000 on the strength of that number, which put it at roughly the
//    62nd percentile of real deals — so about 38% of all deals had Luck's deal
//    half pinned at a full 100%. Calibrate against the code path that ships.
//
// 2. IT FITTED A SINGLE CEILING TO A DISTRIBUTION THAT IS NOT REMOTELY LINEAR.
//    bestEV runs p10 ≈ 2,000, p50 ≈ 6,000, p90 ≈ 44,000, max ≈ 3,500,000 —
//    because HAND_RANKS is odds-proportional, so the mean is dragged around by
//    rare enormous categories (ev-solver.js explains why at length). Dividing
//    by any single ceiling therefore squashes most deals into the bottom of the
//    bar and saturates the rest. Emitting percentile STOPS instead makes the
//    meter uniform by construction: half of deals read above 50% because half
//    of deals ARE above the median, which is what a percentile promises.
//
// The stops go stale whenever HAND_RANKS or the deal path changes. That is what
// tests/meters.test.js's uniformity check is for — it re-samples and fails if
// the table has drifted, rather than letting the meter quietly go wrong again.
import { dealHand, freshSeed } from '../src/core/deck.js';
import { solveOptimalDiscard } from '../src/core/ev-solver.js';

const SAMPLES = Number(process.argv[2] || 1_500);

const bestEVs = [];
for (let i = 0; i < SAMPLES; i++) {
  // The real deal path — rarities and wild flags included.
  const { hand, drawPile } = dealHand(freshSeed());
  // maxDiscards 3 is the default day. Days that allow 4 or 5 (Fourth Chance,
  // Clean Slate) raise everyone's bestEV together, so they shift the whole
  // field rather than one player's standing — see meters.js.
  const { best } = solveOptimalDiscard(hand, drawPile, { maxDiscards: 3 });
  bestEVs.push(best.ev);
  if ((i + 1) % 100 === 0) process.stderr.write(`${i + 1}/${SAMPLES}\n`);
}

bestEVs.sort((a, b) => a - b);
const at = (q) => bestEVs[Math.min(bestEVs.length - 1, Math.floor(bestEVs.length * q))];

// 5-point steps: 21 stops from p0 to p100, interpolated between at runtime.
const stops = Array.from({ length: 21 }, (_, i) => Math.round(at(i / 20)));

console.log(`\n// Generated by tools/calibrate-meters.js from ${SAMPLES} deals.`);
console.log('// bestEV at each 5th percentile, p0 through p100.');
console.log('const DEAL_QUALITY_STOPS = [');
for (let i = 0; i < stops.length; i += 7) {
  console.log(`  ${stops.slice(i, i + 7).join(', ')},`);
}
console.log('];');

// ── The no-discard yardstick ────────────────────────────────────────────────
//
// Double or Nothing (§4e) sets maxDiscards to 0, so "what a perfect player
// could get out of this deal" collapses to "what the five cards are already
// worth". Scored against the stops above — which measure a 3-discard day —
// every player on a wager day reads a deal quality of about 3%, because a pat
// hand is worth a fraction of what the same hand is worth with three draws.
// It is the same category of error as the old single ceiling: a real number
// measured against the wrong distribution.
//
// No solving needed here, so this samples far more deals than the block above.
import { evaluateHand } from '../src/core/hand-evaluator.js';

const PAT_SAMPLES = 40_000;
const patScores = [];
for (let i = 0; i < PAT_SAMPLES; i++) {
  patScores.push(evaluateHand(dealHand(freshSeed()).hand).score);
}
patScores.sort((a, b) => a - b);
const patAt = (q) => patScores[Math.min(patScores.length - 1, Math.floor(patScores.length * q))];
const patStops = Array.from({ length: 21 }, (_, i) => Math.round(patAt(i / 20)));

console.log(`\n// Generated by tools/calibrate-meters.js from ${PAT_SAMPLES.toLocaleString()} deals.`);
console.log('// Opening-hand score at each 5th percentile, p0 through p100.');
console.log('const PAT_QUALITY_STOPS = [');
for (let i = 0; i < patStops.length; i += 7) {
  console.log(`  ${patStops.slice(i, i + 7).join(', ')},`);
}
console.log('];');
